# Generated by Django 6.0.2 on 2026-05-10 21:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('PhoneID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('PhoneNumber', models.CharField(max_length=15, unique=True)),
                ('Name', models.CharField(max_length=150)),
                ('Note', models.TextField(blank=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=25)),
                ('Cost', models.PositiveIntegerField()),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('StoreName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('Store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminsection.store')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=20, unique=True)),
                ('JoiningDate', models.DateField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('Note', models.TextField(blank=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminsection.store')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('Comment', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminsection.employee')),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminsection.service')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.store')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillingNumber', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Note', models.TextField()),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.customer')),
                ('Catagories', models.ManyToManyField(to='adminsection.service')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.store')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('BillAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountType', models.CharField(choices=[('PERCENT', 'Percentage (%)'), ('AMOUNT', 'Fixed Amount (₹)')], default='PERCENT', max_length=10)),
                ('DiscountValue', models.DecimalField(decimal_places=2, default=0, help_text='Enter % value or flat ₹ amount depending on DiscountType', max_digits=10)),
                ('Note', models.TextField(blank=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='adminsection.customer')),
            ],
            options={
                'ordering': ['-VisitDate'],
            },
        ),
    ]
