# Generated by Django 6.0.2 on 2026-02-16 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('Comment', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminsection.employee')),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminsection.service')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.store')),
            ],
        ),
    ]
