# Generated by Django 6.0.2 on 2026-02-23 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='User',
        ),
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
