# Generated by Django 6.0.2 on 2026-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0003_storestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='Services',
            field=models.ManyToManyField(blank=True, related_name='visits', to='adminsection.service'),
        ),
    ]
