# Generated by Django 6.0.2 on 2026-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0004_visit_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Note',
            field=models.TextField(blank=True),
        ),
    ]
