# Generated by Django 6.0.2 on 2026-05-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Note', models.TextField()),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTime', models.TimeField()),
                ('ApplyDate', models.DateTimeField(auto_now_add=True)),
                ('RemarkDate', models.DateTimeField(auto_now=True)),
                ('AppointmentNumber', models.IntegerField(blank=True, null=True)),
                ('Remark', models.CharField(choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.service')),
            ],
        ),
    ]
