# Generated by Django 6.0.2 on 2026-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Note', models.TextField()),
                ('AppoinmentDate', models.DateField()),
                ('AppoinmentTine', models.TimeField()),
                ('ApplyDate', models.DateTimeField(auto_now_add=True)),
                ('RemarkDate', models.DateTimeField(auto_now=True)),
                ('AppointmentNumber', models.IntegerField(blank=True, null=True)),
                ('Remark', models.CharField(choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1)),
                ('Service', models.ManyToManyField(to='adminsection.service')),
            ],
        ),
    ]
