# Generated by Django 6.0.2 on 2026-06-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_visit_store'),
        ('parlour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='adminsection.store'),
        ),
    ]
