# Generated by Django 6.0.2 on 2026-02-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='AppoinmentTine',
            new_name='AppoinmentTime',
        ),
    ]
