# Generated by Django 6.0.2 on 2026-06-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0002_appointment_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Remark',
            field=models.CharField(blank=True, choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1),
        ),
    ]
