# Generated by Django 6.0.2 on 2026-02-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_review'),
        ('parlour', '0002_rename_appoinmenttine_appoinment_appoinmenttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='Service',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='Service',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='adminsection.service'),
            preserve_default=False,
        ),
    ]
