# Generated by Django 6.0.2 on 2026-06-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_visit_store'),
        ('parlour', '0004_alter_appointment_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.store'),
        ),
    ]
